### ISSUE TITLE
Pre-requisites should be updated

### ISSUE THREAD

**Issue by MicFin** [ga-wdi-boston/ruby-diagnostic#144]
Current pre-reqs include:

-   [ga-wdi-boston/ruby-vs-js](https://github.com/ga-wdi-boston/ruby-vs-js)
-   [ga-wdi-boston/ruby-vs-js-arrays](https://github.com/ga-wdi-boston/ruby-vs-js-arrays)
-   [ga-wdi-boston/ruby-vs-js-hash-dictionary](https://github.com/ga-wdi-boston/ruby-vs-js-hash-dictionary)
-   [ga-wdi-boston/ruby-vs-js-array-methods](https://github.com/ga-wdi-boston/ruby-vs-js-array-methods)

Per the calendar it looks like they will actually have been exposed to:

-   [ga-wdi-boston/ruby](https://github.com/ga-wdi-boston/ruby)
-   [ga-wdi-boston/ruby-arrays](https://github.com/ga-wdi-boston/ruby-arrays)
-   [ga-wdi-boston/ruby-hash](https://github.com/ga-wdi-boston/ruby-hash)
-   [ga-wdi-boston/ruby-array-methods](https://github.com/ga-wdi-boston/ruby-array-methods)
-   [ga-wdi-boston/ruby-vs-js-study](https://github.com/ga-wdi-boston/ruby-vs-js-study)
-   [ga-wdi-boston/ruby-vs-js-arrays-study](https://github.com/ga-wdi-boston/ruby-vs-js-arrays-study)
-   [ga-wdi-boston/ruby-vs-js-hash-dictionary-study](https://github.com/ga-wdi-boston/ruby-vs-js-hash-dictionary-study)
-   [ga-wdi-boston/ruby-enumerable-study](https://github.com/ga-wdi-boston/ruby-enumerable-study)

Please advise how we should list the pre-reqs.  Thanks!

**Comment by jrhorn424** [comment]
I believe everything in your second list is OK, but you can drop the `ruby-enumerable-study`.
